CREATE TABLE IF NOT EXISTS Objects (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id INTEGER,
	x INT UNSIGNED DEFAULT 0,
	y int UNSIGNED DEFAULT 0,
	`type` STRING,
    shown INTEGER DEFAULT 0,
    spawntime INTEGER DEFAULT 0,
    updated INTEGER DEFAULT 0
)